import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "de" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translation object
const translations = {
  de: {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome":
      "Willkommen zurück! Hier ist Ihre Sicherheitsmanagement-Übersicht.",
    "dashboard.setupCompany": "Firma einrichten",
    "dashboard.totalEmployees": "Mitarbeiter insgesamt",
    "dashboard.overdueObligations": "Überfällige HSE-Verpflichtungen",
    "dashboard.last7Days": "Letzte 7 Tage",
    "dashboard.incidents": "Vorfallberichte",
    "dashboard.hazards": "Gefahrenmeldungen",
    "dashboard.needsAttention": "⚠️ Benötigt Aufmerksamkeit",
    "dashboard.newReports": "📊 Neue Berichte",
    "dashboard.thisMonth": "+5 diesen Monat",
    "dashboard.healthCheckups": "Gesundheitsuntersuchungen",
    "dashboard.healthCheckupsDesc":
      "Status der Gesundheitsbeurteilungen der Mitarbeiter",
    "dashboard.taskOverview": "Aufgabenübersicht",
    "dashboard.upcomingTasks": "Anstehende Aufgaben",
    "dashboard.completedTasks": "Erledigte Aufgaben",
    "dashboard.showUpcoming": "Anstehende anzeigen",
    "dashboard.showCompleted": "Erledigte anzeigen",
    "dashboard.noTasks": "Keine Aufgaben",
    "dashboard.assignedTo": "Zugewiesen an:",
    "dashboard.unassigned": "Nicht zugewiesen",
    "dashboard.due": "Fällig:",
    "dashboard.notSet": "Nicht festgelegt",
    "dashboard.planned": "Geplant",
    "dashboard.dueStatus": "Fällig",
    "dashboard.completed": "Abgeschlossen",
    "dashboard.cancelled": "Abgebrochen",
    "dashboard.assigned": "Zugewiesen",
    "dashboard.in progress": "In Bearbeitung",
    "dashboard.expired": "Abgelaufen",
    "dashboard.high": "Hoch",
    "dashboard.medium": "Mittel",
    "dashboard.low": "Niedrig",
    "dashboard.urgent": "Dringend",
    "dashboard.normal": "Normal",

    // Profile
    "dashboard.investigationsByStatus": "Untersuchungen nach Status",
    "dashboard.investigationStatusOverview": "Überblick über den Status aller Untersuchungen",
    "dashboard.upcoming": "Anstehend",
    "profile.title": "Profileinstellungen",
    "profile.subtitle": "Verwalten Sie Ihre Kontoinformationen",
    "profile.saveChanges": "Änderungen speichern",
    "profile.general": "Allgemein",
    "profile.security": "Sicherheit",
    "profile.preferences": "Einstellungen",
    "profile.picture": "Profilbild",
    "profile.pictureDesc": "Aktualisieren Sie Ihr Profilbild",
    "profile.changePicture": "Bild ändern",
    "profile.pictureFormat": "JPG, PNG oder GIF. Maximale Größe 2MB",
    "profile.personalInfo": "Persönliche Informationen",
    "profile.personalInfoDesc": "Aktualisieren Sie Ihre persönlichen Daten",
    "profile.firstName": "Vorname",
    "profile.lastName": "Nachname",
    "profile.email": "E-Mail",
    "profile.emailNote": "E-Mail kann nicht geändert werden",
    "profile.role": "Rolle:",
    "profile.companyId": "Firmen-ID:",
    "profile.editProfile": "Profil bearbeiten",
    "profile.changePassword": "Passwort ändern",
    "profile.changePasswordDesc":
      "Aktualisieren Sie Ihr Passwort, um Ihr Konto zu schützen",
    "profile.currentPassword": "Aktuelles Passwort",
    "profile.newPassword": "Neues Passwort",
    "profile.confirmPassword": "Neues Passwort bestätigen",
    "profile.updatePassword": "Passwort aktualisieren",
    "profile.twoFactor": "Zwei-Faktor-Authentifizierung",
    "profile.twoFactorDesc":
      "Fügen Sie Ihrem Konto eine zusätzliche Sicherheitsebene hinzu",
    "profile.enable2FA": "2FA aktivieren",
    "profile.notifications": "Benachrichtigungen",
    "profile.notificationsDesc":
      "Verwalten Sie, wie Sie Benachrichtigungen erhalten",
    "profile.emailNotifications": "E-Mail-Benachrichtigungen",
    "profile.emailNotificationsDesc":
      "Erhalten Sie E-Mail-Updates über Ihre Aktivitäten",
    "profile.smsNotifications": "SMS-Benachrichtigungen",
    "profile.smsNotificationsDesc":
      "Erhalten Sie SMS-Benachrichtigungen für dringende Angelegenheiten",
    "profile.languageSettings": "Spracheinstellungen",
    "profile.languageSettingsDesc": "Wählen Sie Ihre bevorzugte Sprache",
    "profile.language": "Sprache",
    "profile.german": "Deutsch",
    "profile.english": "Englisch",
    "profile.updated": "Profil aktualisiert",
    "profile.updatedDesc":
      "Ihre Profilinformationen wurden erfolgreich gespeichert.",

    // Common
    "common.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.edit": "Bearbeiten",
    "common.delete": "Löschen",
    "common.loading": "Lädt...",
    "common.note": "Hinweis",

    // Employees
    "employees.title": "Mitarbeiter",
    "employees.description":
      "Verwalten Sie die Mitarbeiterdaten Ihres Unternehmens",
    "employees.addEmployee": "Mitarbeiter hinzufügen",
    "employees.addNew": "Neuen Mitarbeiter hinzufügen",
    "employees.enterDetails": "Geben Sie die Mitarbeiterdaten ein",
    "employees.employeeNumber": "Mitarbeiternummer",
    "employees.firstName": "Vorname",
    "employees.lastName": "Nachname",
    "employees.email": "E-Mail",
    "employees.emailOptional": "E-Mail (Optional)",
    "employees.jobRole": "Berufsbezeichnung",
    "employees.jobRolePlaceholder": "Berufsbezeichnung eingeben oder auswählen",
    "employees.department": "Abteilung",
    "employees.departmentPlaceholder": "Abteilung eingeben oder auswählen",
    "employees.hireDate": "Einstellungsdatum",
    "employees.status": "Status",
    "employees.active": "Aktiv",
    "employees.inactive": "Inaktiv",
    "employees.search": "Mitarbeiter suchen...",
    "employees.noEmployees": "Keine Mitarbeiter gefunden",
    "employees.adding": "Wird hinzugefügt...",
    "employees.addSuccess": "Mitarbeiter erfolgreich hinzugefügt",
    "employees.addError": "Fehler beim Hinzufügen des Mitarbeiters",
    "employees.loadError": "Fehler beim Laden der Mitarbeiter",
    "employees.noDeletePermission": "Sie haben keine Berechtigung, Mitarbeiter zu löschen",
    "employees.noCreatePermission": "Sie haben keine Berechtigung, Mitarbeiter zu erstellen",
    "employees.noEditPermission": "Sie haben keine Berechtigung, Mitarbeiter zu bearbeiten",
    "employees.name": "Name",
    "employees.filterStatus": "Status Filter",
    "employees.filterDepartment": "Abteilungs-Filter",
    "employees.allEmployees": "Alle Mitarbeiter",
    "employees.activeOnly": "Nur Aktive",
    "employees.inactiveOnly": "Nur Inaktive",
    "employees.allDepartments": "Alle Abteilungen",
    "employees.selectDepartment": "Abteilung auswählen",
    "employees.details": "Mitarbeiterdetails & Datensätze",
    "employees.info": "Info",
    "employees.riskProfile": "Risikoprofil",
    "employees.training": "Schulung",
    "employees.tasks": "Aufgaben",
    "employees.exposureGroup": "Expositionsgruppe",
    "employees.riskAssignments":
      "Risikobewertungen, die diesem Mitarbeiter zugewiesen sind, werden hier angezeigt.",
    "employees.trainingRecords":
      "Schulungsunterlagen für diesen Mitarbeiter werden hier angezeigt.",
    "employees.assignedTasks":
      "Aufgaben, die diesem Mitarbeiter zugewiesen sind, werden hier angezeigt.",
    "employees.required": "Erforderlich",
    "employees.optional": "Optional",
    "employees.enterJobRole":
      "Berufsbezeichnung eingeben (z.B. Sicherheitsbeauftragter)",
    "employees.noCompanyId":
      "Keine Firmen-ID gefunden. Sie müssen zuerst einem Unternehmen zugewiesen werden.",
    "employees.import": "Importieren",
    "employees.export": "Exportieren",
    "employees.importEmployees": "Mitarbeiter importieren",
    "employees.exportAs": "Exportieren als",
    "employees.selectFile": "Datei auswählen (.xlsx, .xls, .csv)",
    "employees.importSuccess": "Mitarbeiter erfolgreich importiert",
    "employees.importError": "Fehler beim Importieren der Mitarbeiter",
    "employees.exportSuccess": "Mitarbeiter erfolgreich exportiert",
    "employees.exportError": "Fehler beim Exportieren der Mitarbeiter",
    "employees.importing": "Wird importiert...",
    "employees.exporting": "Wird exportiert...",
    "employees.invalidFile": "Ungültige Datei. Bitte .xlsx, .xls oder .csv verwenden",
    "employees.noValidData": "Keine gültigen Daten in der Datei gefunden",

    // Navigation / Layout
    "nav.dashboard": "Übersicht",
    "nav.employees": "Mitarbeiter",
    "nav.messages": "Nachrichten",
    "nav.investigations": "Untersuchungen",
    "nav.riskAssessments": "Risikobewertungen",
    "nav.measures": "Maßnahmen",
    "nav.training": "Schulungen",
    "nav.trainings": "Schulungen",
    "nav.incidents": "Vorfälle",
    "nav.audits": "Sicherheitsaudits",
    "nav.reports": "Berichte",
    "nav.settings": "Einstellungen",
    "nav.hseHub": "HSE Hub",
    "nav.welcomeToHseHub": "Willkommen bei HSE Hub",
    "nav.profile": "Profil",
    "nav.invoices": "Rechnungen",
    "nav.darkMode": "Dunkelmodus",
    "nav.language": "Sprache",
    "nav.signOut": "Abmelden",
    "nav.logout": "Abmelden",
    "nav.company": "Unternehmen",
    "nav.user": "Benutzer",

    // Super Admin
    "superadmin.dashboard": "Super Admin Dashboard",
    "superadmin.manageCompanies": "Unternehmen verwalten",
    "superadmin.manageSubscriptions": "Abonnements verwalten",
    "superadmin.viewAnalytics": "Analysen anzeigen",

    // Messages
    "messages.title": "Nachrichten",
    "messages.searchChannels": "Kanäle durchsuchen...",
    "messages.channels": "Kanäle",
    "messages.directMessages": "Direktnachrichten",
    "messages.newChannel": "Neuer Kanal",
    "messages.newMessage": "Neue Nachricht",
    "messages.selectChannel": "Kanal auswählen",
    "messages.selectChannelDesc":
      "Wählen Sie einen Kanal aus, um die Konversation zu starten",
    "messages.typeMessage": "Nachricht eingeben...",
    "messages.send": "Senden",
    "messages.messageSent": "Nachricht gesendet",
    "messages.messageDelivered": "Ihre Nachricht wurde zugestellt.",
    "messages.noMessages": "Keine Nachrichten noch. Starten Sie das Gespräch!",
    "messages.members": "Mitglieder",
    "messages.companyChannel": "Firmenweiter Kanal",
    "messages.directMessage": "Direktnachricht",
    "messages.messagePlaceholder": "Nachricht an",
    "messages.sendInstructions":
      "Drücken Sie Enter zum Senden, Umschalt+Enter für neue Zeile",

    // Investigations
    "investigations.title": "Untersuchungen",
    "investigations.manage": "Vorfalluntersuchungen verwalten",
    "investigations.new": "Neue Untersuchung",
    "investigations.edit": "Bearbeiten",
    "investigations.id": "Untersuchungs-ID",
    "investigations.relatedIncident": "Zugehöriger Vorfall",
    "investigations.startDate": "Startdatum",
    "investigations.assignedTo": "Zugewiesen an",
    "investigations.status": "Status",
    "investigations.priority": "Priorität",
    "investigations.description": "Beschreibung",
    "investigations.findings": "Ergebnisse",
    "investigations.recommendations": "Empfehlungen",
    "investigations.search": "Untersuchungen durchsuchen...",
    "investigations.exportPDF": "Als PDF exportieren",
    "investigations.filterStatus": "Status filtern",
    "investigations.filterPriority": "Priorität filtern",
    "investigations.open": "Offen",
    "investigations.inProgress": "In Bearbeitung",
    "investigations.completed": "Abgeschlossen",
    "investigations.planned": "Geplant",
    "investigations.closed": "Geschlossen",
    "investigations.low": "Niedrig",
    "investigations.medium": "Mittel",
    "investigations.high": "Hoch",
    "investigations.critical": "Kritisch",
    "investigations.unassigned": "Nicht zugewiesen",
    "investigations.actions": "Aktionen",
    "investigations.allInvestigations": "Alle Untersuchungen",
    "investigations.employeesWithInvestigations":
      "Mitarbeiter mit G-Untersuchungen (geplant/fällig nach Filter)",
    "investigations.termsDueDates":
      "Termine und Fälligkeiten (pro Untersuchung)",
    "investigations.overview": "Übersicht der Gesundheitsuntersuchungen",
    "investigations.employeeView": "Mitarbeiter-Ansicht",
    "investigations.dateView": "Termin-Ansicht",
    "investigations.newInvestigation": "Neue Untersuchung",
    "investigations.editInvestigation": "Untersuchung bearbeiten",
    "investigations.investigationDetails":
      "Geben Sie die Details der G-Untersuchung ein",
    "investigations.gCode": "G-Code",
    "investigations.employee": "Mitarbeiter",
    "investigations.selectEmployee": "Mitarbeiter wählen",
    "investigations.none": "Keiner",
    "investigations.dueDate": "Fällig am",
    "investigations.appointmentDate": "Termin",
    "investigations.doctor": "Arzt",
    "investigations.doctorName": "Name des Arztes",
    "investigations.investigationDescription": "Beschreibung der Untersuchung",
    "investigations.cancel": "Abbrechen",
    "investigations.update": "Aktualisieren",
    "investigations.create": "Erstellen",
    "investigations.employees": "Mitarbeiter",
    "investigations.appointments": "Termine",
    "investigations.searchPlaceholder": "Suche (Name, Abteilung)",
    "investigations.plannedOrDue": "Geplant oder Fällig",
    "investigations.allTypes": "Alle Arten",
    "investigations.allDepartments": "Alle Abteilungen",
    "investigations.allGroups": "Alle Gruppen",
    "investigations.fromDate": "Von Datum",
    "investigations.toDate": "Bis Datum",
    "investigations.name": "Name",
    "investigations.checkupView": "Checkup-Ansicht",
    "investigations.firstName": "Vorname",
    "investigations.department": "Abteilung",
    "investigations.location": "Standort",
    "investigations.group": "Gruppe",
    "investigations.gInvestigations": "G-Untersuchungen",
    "investigations.noInvestigations":
      "Keine Untersuchungen gefunden. Erstellen Sie eine neue.",
    "investigations.investigation": "Untersuchung",
    "investigations.success": "Erfolg",
    "investigations.investigationUpdated":
      "Untersuchung erfolgreich aktualisiert",
    "investigations.updated": "Untersuchung erfolgreich aktualisiert",
    "investigations.created": "Untersuchung erfolgreich erstellt",
    "investigations.noResults": "Keine Untersuchungen gefunden",

    // Health Check-Ups
    "checkups.title": "Untersuchungen (G-Untersuchungen)",
    "checkups.description": "Gesundheitsuntersuchungen und medizinische Untersuchungen verwalten",
    "checkups.addCheckup": "Untersuchung hinzufügen",
    "checkups.noCheckups": "Keine Untersuchungen geplant",
    "checkups.done": "Erledigt",
    "checkups.due": "Fällig",
    "checkups.planned": "Geplant",
    "checkups.open": "Offen",
    "checkups.investigation": "Untersuchung",
    "checkups.dueDate": "Fällig",
    "checkups.completed": "Abgeschlossen",
    "checkups.appointment": "Termin",
    "checkups.complete": "Abschließen",
    "checkups.uploadCertificate": "Nachweis hochladen",

    // Risk Assessments
    "risks.title": "Risikobewertungen",
    "risks.subtitle": "Gefährdungsbeurteilungen verwalten",
    "risks.new": "Neue Risikobewertung",
    "risks.riskTitle": "Risikotitel",
    "risks.description": "Beschreibung",
    "risks.category": "Risikokategorie",
    "risks.department": "Abteilung",
    "risks.likelihood": "Wahrscheinlichkeit",
    "risks.severity": "Schweregrad",
    "risks.riskScore": "Risikobewertung",
    "risks.riskLevel": "Risikoniveau",
    "risks.mitigation": "Schutzmaßnahmen",
    "risks.assessmentDate": "Bewertungsdatum",
    "risks.search": "Risiken durchsuchen...",
    "risks.selectCategory": "Kategorie auswählen",
    "risks.selectDepartment": "Abteilung auswählen",
    "risks.critical": "Kritisch",
    "risks.high": "Hoch",
    "risks.medium": "Mittel",
    "risks.low": "Niedrig",
    "risks.basicInformation": "Grundinformationen",
    "risks.hazardAssessment": "Gefährdungen, Bewertung & Maßnahmen",
    "risks.measures": "Maßnahmen (Measures)",
    "risks.hazardCategory": "Kategorie (Hazard Categories dropdown)",
    "risks.selectHazardCategory": "Auswählen...",
    "risks.shortDescription": "Beschreibung (Description)",
    "risks.shortDescriptionPlaceholder": "Kurzbeschreibung",
    "risks.primaBefore": "PRIMA: (before)",
    "risks.postAfter": "POST: (after)",
    "risks.probabilityBefore":
      "Eintritts-Wahrsch. (vorher) - Probability of occurrence (before)",
    "risks.probabilityAfter":
      "Eintritts-Wahrsch. (nachher) - Probability of occurrence (after)",
    "risks.damageExtentBefore":
      "Schadensausmaß (vorher) - Extent of damage (before)",
    "risks.damageExtentAfter":
      "Schadensausmaß (nachher) - Extent of damage (after)",
    "risks.riskScoreCalculated": "Risk Score (calculated)",
    "risks.location": "Location",
    "risks.selectLocation": "Select location",
    "risks.exposureGroup": "Exposure Group",
    "risks.selectExposureGroup": "Select exposure group",
    "risks.lineManager": "Benutzer",
    "risks.selectLineManager": "Benutzer auswählen",
    "risks.responsiblePerson": "Verantwortliche Person (Responsible Person)",
    "risks.selectManager": "Select manager",
    "risks.dueDate": "Termin (Due Date)",
    "risks.uploadDocuments": "Upload Documents",
    "risks.chooseFile": "Datei auswählen | Keine ausgewählt",
    "risks.addMeasure": "+ Maßnahme (Button, to add more measures)",
    "risks.addMeasureButton": "Add Measure",
    "risks.buildingBlock": "Building Block",
    "risks.selectBuildingBlock": "Select building block",
    "risks.progressStatus": "Progress Status",
    "risks.notStarted": "Not Started",
    "risks.notes": "Notes",
    "risks.back": "← Back",
    "risks.nextSlide": "Next Slide →",
    "risks.step1": "Schritt 1",
    "risks.step2": "Schritt 2",
    "risks.step3": "Schritt 3",

    // Measures
    "measures.title": "Maßnahmen & Kontrollen",
    "measures.subtitle": "Maßnahmen zur Risikominderung verfolgen",
    "measures.new": "Neue Maßnahme",
    "measures.edit": "Maßnahme bearbeiten",
    "measures.measureTitle": "Maßnahmentitel",
    "measures.description": "Beschreibung",
    "measures.type": "Maßnahmentyp",
    "measures.status": "Status",
    "measures.responsiblePerson": "Verantwortliche Person",
    "measures.dueDate": "Fälligkeitsdatum",
    "measures.completionDate": "Abschlussdatum",
    "measures.verificationMethod": "Verifikationsmethode",
    "measures.search": "Maßnahmen durchsuchen...",
    "measures.exportPDF": "Als PDF exportieren",
    "measures.filterStatus": "Status filtern",
    "measures.filterType": "Typ filtern",
    "measures.preventive": "Präventiv",
    "measures.corrective": "Korrigierend",
    "measures.improvement": "Verbesserung",
    "measures.planned": "Geplant",
    "measures.inProgress": "In Bearbeitung",
    "measures.completed": "Abgeschlossen",
    "measures.cancelled": "Abgebrochen",
    "measures.actions": "Aktionen",
    "measures.noDeadline": "Keine Frist",

    // Training
    "training.title": "Schulungen",
    "training.subtitle": "Schulung & Qualifikationsmanagement",
    "training.records": "Schulungsunterlagen",
    "training.assign": "Schulung zuweisen",
    "training.employee": "Mitarbeiter",
    "training.trainingType": "Schulungstyp",
    "training.assignedDate": "Zugewiesenes Datum",
    "training.expiryDate": "Ablaufdatum",
    "training.status": "Status",
    "training.search": "Schulungen durchsuchen...",
    "training.selectEmployee": "Mitarbeiter auswählen",
    "training.selectType": "Schulungstyp auswählen",
    "training.assigned": "Zugewiesen",
    "training.inProgress": "In Bearbeitung",
    "training.completed": "Abgeschlossen",
    "training.expired": "Abgelaufen",
    "training.actions": "Aktionen",
    "training.createCourse": "Kurs erstellen",
    "training.courseName": "Kursname",
    "training.courseDescription": "Kursbeschreibung",
    "training.courseContent": "Kursinhalte",
    "training.manageLessons": "Lektionen und Inhalte für diesen Kurs verwalten",
    "training.addLesson": "Lektion hinzufügen",
    "training.uploadLessons": "Lektionen hochladen",
    "training.newLesson": "Neue Lektion",
    "training.lessonName": "Lektionsname",
    "training.lessonType": "Typ",
    "training.noCourses": "Keine Schulungsunterlagen gefunden",
    "training.noCoursesDesc":
      "Schulung den Mitarbeitern zuweisen, um zu beginnen",
    "training.noLessons": "Noch keine Lektionen",
    "training.noLessonsDesc":
      'Klicken Sie auf "Lektion hinzufügen", um Inhalte hinzuzufügen',
    "training.draft": "Entwurf",
    "training.published": "Veröffentlicht",
    "training.unterkapitel": "Unterkapitel",
    "training.videoAudio": "Video/Audio",
    "training.pdf": "PDF",
    "training.text": "Text",
    "training.websiteLink": "Website-Link",
    "training.zipFile": "ZIP-Datei",
    "training.videoLink": "Video-Link",
    "training.pdfLink": "PDF-Link",
    "training.websiteLinkUrl": "Website-URL",
    "training.zipFileLink": "ZIP-Datei-Link",
    "training.textContent": "Textinhalt",
    "training.enterTextContent": "Geben Sie den Textinhalt ein...",
    "training.lessonDetails": "Lektionsdetails",
    "training.openLink": "Link öffnen",
    "training.cancel": "Abbrechen",
    "training.lesson": "Lektion",
    "training.general": "Allgemein",
    "training.chapters": "Kapitel",
    "training.videoAudioLesson": "Video/Audio Lektion",
    "training.learnMoreEditor": "Erfahre mehr über den Kurseditor",
    "training.enterLessonName": "Lektionsname eingeben",
    "training.shortDescription": "Kurzbeschreibung",
    "training.shortDescriptionPlaceholder": "Kurze Beschreibung der Lektion...",
    "training.videoAudioNote": "Hinweis zu Video- und Audioformaten",
    "training.videoAudioFormats": "Video & Audioformate bis zu 25GB",
    "training.recordVideo": "Video aufnehmen",
    "training.importVideo": "Video importieren",
    "training.manageChapters": "Kapitel verwalten",
    "training.addLessonsToSubchapter": "Fügen Sie Lektionen zu diesem Unterkapitel hinzu",
    "training.chapterManagementComingSoon": "Kapitel-Verwaltung wird in Kürze verfügbar sein",
    "common.saving": "Speichern...",

    // Incidents
    "incidents.title": "Vorfälle & Untersuchungen",
    "incidents.description":
      "Arbeitsplatzvorfälle, Beinahe-Unfälle und Verletzungen mit Ursachenanalyse verfolgen",
    "incidents.subtitle": "Vorfälle & Beinahe-Unfälle",
    "incidents.new": "Neuer Vorfall",
    "incidents.edit": "Vorfall bearbeiten",
    "incidents.incidentNumber": "Vorfallnr.",
    "incidents.incidentTitle": "Vorfallstitel",
    "incidents.type": "Typ",
    "incidents.severity": "Schweregrad",
    "incidents.date": "Datum",
    "incidents.location": "Ort",
    "incidents.department": "Abteilung",
    "incidents.affectedEmployee": "Betroffener Mitarbeiter",
    "incidents.reportedBy": "Gemeldet von",
    "incidents.rootCause": "Ursachenanalyse",
    "incidents.immediateActions": "Sofortmaßnahmen",
    "incidents.investigationStatus": "Untersuchungsstatus",
    "incidents.search": "Vorfälle durchsuchen...",
    "incidents.searchPlaceholder": "Vorfälle durchsuchen...",
    "incidents.filterType": "Nach Typ filtern",
    "incidents.filterByType": "Nach Typ filtern",
    "incidents.filterSeverity": "Nach Schweregrad filtern",
    "incidents.filterBySeverity": "Nach Schweregrad filtern",
    "incidents.injury": "Verletzung",
    "incidents.nearMiss": "Beinahe-Unfall",
    "incidents.propertyDamage": "Sachschaden",
    "incidents.environmental": "Umwelt",
    "incidents.other": "Sonstige",
    "incidents.minor": "Geringfügig",
    "incidents.moderate": "Mäßig",
    "incidents.serious": "Schwerwiegend",
    "incidents.critical": "Kritisch",
    "incidents.fatal": "Tödlich",
    "incidents.actions": "Aktionen",
    "incidents.total": "Vorfälle insgesamt",
    "incidents.injuries": "Verletzungen",
    "incidents.nearMisses": "Beinahe-Unfälle",
    "incidents.underInvestigation": "In Untersuchung",
    "incidents.reports": "Vorfallberichte",
    "incidents.reportsDesc":
      "Vollständige Liste aller Arbeitsplatzvorfälle und Beinahe-Unfälle",
    "incidents.reportIncident": "Vorfall melden",
    "incidents.editIncident": "Vorfall bearbeiten",
    "incidents.reportNew": "Neuen Vorfall melden",
    "incidents.documentDesc":
      "Arbeitsplatzvorfall oder Beinahe-Unfall zur Untersuchung dokumentieren",
    "incidents.titlePlaceholder": "Kurze Beschreibung des Vorfalls",
    "incidents.descriptionPlaceholder":
      "Detaillierte Beschreibung dessen, was passiert ist",
    "incidents.locationPlaceholder": "Wo ist es passiert?",
    "incidents.selectDepartment": "Abteilung auswählen",
    "incidents.selectEmployee": "Mitarbeiter auswählen",
    "incidents.immediateActionsPlaceholder":
      "Was wurde unmittelbar nach dem Vorfall getan?",
    "incidents.rootCausePlaceholder": "Was hat diesen Vorfall verursacht?",
    "incidents.open": "Offen",
    "incidents.inProgress": "In Bearbeitung",
    "incidents.closed": "Geschlossen",
    "incidents.report": "Melden",
    "incidents.incident": "Vorfall",
    "incidents.allTypes": "Alle Typen",
    "incidents.allSeverities": "Alle Schweregrade",
    "incidents.noIncidents":
      "Keine Vorfälle gefunden. Melden Sie einen, um zu beginnen.",
    "incidents.status": "Status",
    "incidents.affected": "Betroffen",

    // Audits
    "audits.title": "Audits",
    "audits.subtitle": "Sicherheitsaudits",
    "audits.new": "Neues Audit",
    "audits.auditTitle": "Audit-Titel",
    "audits.category": "Audit-Kategorie",
    "audits.department": "Abteilung",
    "audits.scheduledDate": "Geplantes Datum",
    "audits.status": "Status",
    "audits.findings": "Ergebnisse",
    "audits.deficiencies": "Gefundene Mängel",
    "audits.search": "Audits durchsuchen...",
    "audits.selectCategory": "Kategorie auswählen",
    "audits.selectDepartment": "Abteilung auswählen",
    "audits.planned": "Geplant",
    "audits.inProgress": "In Bearbeitung",
    "audits.completed": "Abgeschlossen",
    "audits.actions": "Aktionen",
    "audits.isoStandard": "ISO Standard",
    "audits.selectISOStandard": "ISO Standard wählen",
    "audits.responsiblePerson": "Verantwortliche Person",
    "audits.selectPerson": "Person auswählen",
    "audits.scope": "Umfang",
    "audits.scopePlaceholder": "z.B. Kein Umfang definiert",
    "audits.allStatus": "Alle Status",
    "audits.allTemplates": "Alle Templates",
    "audits.template": "Template",
    "audits.progress": "Fortschritt",
    "audits.details": "Details",
    "audits.pdf": "PDF",
    "audits.delete": "Löschen",
    "audits.deleteConfirm": "Audit löschen?",
    "audits.deleteMessage": "Möchten Sie das Audit wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
    "audits.createAudit": "Audit erstellen",
    "audits.notAssigned": "Nicht zugewiesen",
    "audits.noAudits": "Keine Audits gefunden",
    "audits.createFirst": "Erstellen Sie Ihr erstes Audit",
    "audits.auditCenter": "Audit- und Compliance-Center",
    "audits.standardizedAudits": "Standardisierte Audits, Reports und Nachweise",
    "audits.checklist": "Checkliste",
    "audits.checklistItems": "Prüfpunkte",
    "audits.status.pending": "Ausstehend",
    "audits.status.completed": "Abgeschlossen",
    "audits.status.failed": "Nicht Bestanden",
    "audits.status.notApplicable": "Nicht zugetreffend",
    "audits.notes": "Notizen",
    "audits.notesPlaceholder": "Notizen zu diesem Prüfpunkt...",
    "audits.pdfExport": "PDF Export",
    "audits.descriptionPlaceholder": "Beschreibung des Audits...",

    // Common Actions
    "common.create": "Erstellen",
    "common.update": "Aktualisieren",
    "common.submit": "Absenden",
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.export": "Exportieren",
    "common.all": "Alle",
    "common.none": "Keine",
    "common.select": "Auswählen",
    "common.optional": "Optional",
    "common.required": "Erforderlich",
    "common.actions": "Aktionen",
    "common.by": "Von",
    "common.status": "Status",
    "common.close": "Schließen",
    "common.success": "Erfolg",
    "common.error": "Fehler",
    "common.savingError": "Fehler beim Speichern",
    "common.createdOn": "Erstellt am",
    "common.pdfExported": "PDF erfolgreich exportiert",
    "common.lastName": "Nachname",
    "common.firstName": "Vorname",
    "common.department": "Abteilung",
    "common.location": "Standort",
    "common.group": "Gruppe",
    "common.employee": "Mitarbeiter",
    "common.allDepartments": "Alle Abteilungen",
    "common.allGroups": "Alle Gruppen",
    "common.fromDate": "Von Datum",
    "common.toDate": "Bis Datum",
    "common.pickDate": "Datum wählen",
    "common.yes": "Ja",
    "common.no": "Nein",

    // Reports
    "reports.title": "HSE Berichte & Analysen",
    "reports.subtitle": "Umfassende Compliance- und Leistungs-Dashboards",
    "reports.exportPDF": "Als PDF exportieren",
    "reports.totalEmployees": "Mitarbeiter insgesamt",
    "reports.activeWorkforce": "Aktive Belegschaft",
    "reports.riskAssessments": "Risikobewertungen",
    "reports.totalGBU": "GBU-Bewertungen insgesamt",
    "reports.safetyAudits": "Sicherheitsaudits",
    "reports.completed": "abgeschlossen",
    "reports.trainingCompliance": "Schulungskonformität",
    "reports.overview": "Übersicht",
    "reports.trainingMatrix": "Schulungsmatrix",
    "reports.incidents": "Vorfälle",
    "reports.measures": "Maßnahmen",
    "reports.auditCompletion": "Audit-Abschlussstatus",
    "reports.auditMetrics": "Sicherheitsaudit-Leistungsmetriken",
    "reports.totalAudits": "Audits insgesamt",
    "reports.taskCompletion": "Aufgabenabschlussstatus",
    "reports.taskTracking": "Korrekturmaßnahmen-Verfolgung",
    "reports.totalTasks": "Aufgaben insgesamt",

    // Settings
    "settings.title": "Einstellungen",
    "settings.subtitle": "Systemkonfiguration",
    "settings.team": "Team",
    "settings.teamDesc": "Team-Mitglieder einladen und verwalten",
    "settings.userRoles": "Benutzerrollen & Berechtigungen (RBAC)",
    "settings.rolesDesc":
      "Rollen definieren und Zugriffsberechtigungen im System festlegen",
    "settings.permissionUpdated": "Berechtigung erfolgreich aktualisiert",
    "settings.configuration": "Konfiguration",
    "settings.configDesc": "Standorte, Abteilungen, Genehmigungen",
    "settings.catalogs": "Kataloge & Inhalte",
    "settings.catalogsDesc": "Gefahren, Maßnahmen, Risikomatrix",
    "settings.intervals": "Intervalle und Fristen",
    "settings.intervalsDesc": "Risikobewertungen, Audits, Benachrichtigungen",
    "settings.medicalCare": "Arbeitsmedizinische Vorsorge",
    "settings.medicalDesc": "G-Untersuchungsliste",
    "settings.profileFields": "Profile-Felder",
    "settings.profileFieldsDesc": "Eigene Felder definieren",
    "settings.profileFieldsTitle": "Profile-Felder",
    "settings.profileFieldsSubtitle": "Erstellen Sie Vorlagen mit Feldern für Kandidat*innen-Profile. Vorlagen können im Editor als Jobs zugeordnet werden",
    "settings.addProfileField": "Feld hinzufügen",
    "settings.fieldName": "Feldname",
    "settings.fieldLabel": "Feldbezeichnung",
    "settings.fieldType": "Feldtyp",
    "settings.extractedFromResume": "Aus Lebenslauf extrahiert",
    "settings.fieldRequired": "Pflichtfeld",
    "settings.fieldTypeText": "Text",
    "settings.fieldTypeNumber": "Nummer",
    "settings.fieldTypeDate": "Datum",
    "settings.fieldTypeBoolean": "Ja/Nein",
    "settings.fieldTypeSelect": "Auswahl",
    "settings.noProfileFields": "Keine Felder gefunden. Erstellen Sie Ihr erstes Feld.",
    "settings.addRole": "Benutzerdefinierte Rolle hinzufügen",
    "settings.createRole": "Benutzerdefinierte Rolle erstellen",
    "settings.roleDesc":
      "Geben Sie einen Namen für die neue Rolle ein. Sie können die Berechtigungen nach der Erstellung konfigurieren.",
    "settings.rolePlaceholder": "Rollenname (z.B. Projektleiter)",
    "settings.role": "Rolle",
    "settings.dashboard": "Dashboard",
    "settings.employees": "Mitarbeiter",
    "settings.healthCheckups": "Gesundheitsuntersuchungen",
    "settings.documents": "Dokumente",
    "settings.reports": "Berichte",
    "settings.audits": "Audits",
    "settings.settings": "Einstellungen",
    "settings.teamManagement": "Team-Management",
    "settings.teamManagementDesc":
      "Team-Mitglieder, deren Zugriff und Benutzerrollen verwalten",
    "settings.addTeamMember": "Team-Mitglied hinzufügen",
    "settings.firstName": "Vorname",
    "settings.lastName": "Nachname",
    "settings.enterFirstName": "Vorname eingeben",
    "settings.enterLastName": "Nachname eingeben",
    "settings.enterEmail": "E-Mail eingeben",
    "settings.userRole": "Benutzerrolle",
    "settings.selectRole": "Rolle auswählen",
    "settings.name": "Name",
    "settings.email": "E-Mail",
    "settings.status": "Status",
    "settings.noTeamMembers":
      "Keine Team-Mitglieder gefunden. Team-Mitglieder hinzufügen, um sie zur Plattform einzuladen.",
    "settings.locations": "Standorte",
    "settings.locationsDesc": "Firmenstandorte und -standorte verwalten",
    "settings.locationManagement": "Standortverwaltung kommt bald...",
    "settings.departments": "Abteilungen",
    "settings.approvalProcess": "Genehmigungsprozess",
    "settings.approvalProcessDesc":
      "Genehmigungsworkflows konfigurieren (Abteilung → Genehmiger)",
    "settings.addApprovalWorkflow": "Genehmigungsworkflow hinzufügen",
    "settings.selectDepartment": "Abteilung auswählen",
    "settings.department": "Abteilung",
    "settings.approver": "Genehmiger",
    "settings.selectApprover": "Genehmiger auswählen",
    "settings.noApprovalWorkflows":
      "Keine Genehmigungsworkflows konfiguriert. Fügen Sie oben Abteilungen hinzu, um zu beginnen.",
    "settings.exposureGroups": "Expositionsgruppen",
    "settings.hazardCategories": "Gefahrenkategorien",
    "settings.hazardCategoriesDesc":
      "Gefahrenschweregrade verwalten - Vordefinierte Werte können nicht gelöscht werden",
    "settings.addCustomCategory": "Benutzerdefinierte Kategorie hinzufügen",
    "settings.addCustomHazardCategory":
      "Benutzerdefinierte Gefahrenkategorie hinzufügen",
    "settings.createCustomHazardCategory":
      "Erstellen Sie eine benutzerdefinierte Gefahrenkategorie für Ihre Organisation",
    "settings.categoryName": "Kategoriename",
    "settings.predefined": "Vordefiniert",
    "settings.custom": "Benutzerdefiniert",
    "settings.measureBuildingBlocks": "Maßnahmenbausteine",
    "settings.measureBuildingBlocksDesc":
      "Wiederverwendbare Maßnahmenvorlagen definieren",
    "settings.measureManagement": "Maßnahmenbausteine kommen bald...",
    "settings.isoSelection": "ISO-Auswahl & Kriterien",
    "settings.isoSelectionDesc":
      "Anwendbare ISO-Standards auswählen und Kriterien konfigurieren",
    "settings.selectISOStandards": "ISO-Standards auswählen",
    "settings.customISOStandards": "Benutzerdefinierte ISO-Standards",
    "settings.enterISOName": "ISO-Name eingeben (z.B. ISO 27001)",
    "settings.add": "Hinzufügen",
    "settings.criteriaForISOs": "Kriterien für ausgewählte ISOs",
    "settings.compact": "Kompakt",
    "settings.complete": "Vollständig",
    "settings.criteria": "Kriterien",
    "settings.criteriaNote":
      "Kriterien müssen oben angepasst werden; je nachdem, was ausgewählt wurde, erscheinen sie oder nicht.",
    "settings.enterNewCriterion": "Neues Kriterium eingeben...",
    "settings.criteriaInfoNote":
      "Die ausgewählten Kriterien werden bei der Erstellung von Audits und Checklisten verwendet. Sie können jederzeit benutzerdefinierte Kriterien hinzufügen oder entfernen.",
    "settings.isoCriteriaManagement": "ISO Kriterien-Verwaltung",
    "settings.isoCriteriaManagementDesc": "Kriterien für ausgewählte ISO-Standards anzeigen und verwalten",
    "settings.noISOSelected": "Keine ISO-Standards ausgewählt",
    "settings.selectISOAbove": "Wählen Sie oben einen ISO-Standard aus, um seine Kriterien anzuzeigen",
    "settings.sections": "Abschnitte",
    "settings.subsections": "Unterabschnitte",
    "settings.implemented": "Umgesetzt",
    "settings.satisfied": "Zufrieden",
    "settings.addItem": "Hinzufügen",
    "settings.editItem": "Bearbeiten",
    "settings.addDetails": "Zusätzliche Details oder Notizen hinzufügen...",
    "settings.noItems": "Keine Elemente gefunden. Klicken Sie auf",
    "settings.toCreate": "zum Erstellen",
    "settings.adding": "Wird hinzugefügt...",
    "settings.success": "Erfolg",
    "settings.categoryCreated": "Kategorie erfolgreich erstellt",
    "settings.error": "Fehler",
    "settings.apiIntegration": "API-Integration",
    "settings.apiIntegrationDesc":
      "Externe Systeme verbinden und API-Zugriff verwalten",
    "settings.apiIntegrationNav": "Externe Systemverbindungen",
    "settings.apiToken": "API-Token",
    "settings.generateNewToken": "Neuen Token generieren",
    "settings.apiTokenDesc":
      "Verwenden Sie diesen Token, um API-Anfragen von externen Systemen zu authentifizieren",
    "settings.apiDocumentation": "API-Dokumentation",
    "settings.baseUrl": "Basis-URL:",
    "settings.apiDocsDesc":
      "Vollständige API-Dokumentation und Integrationsleitfäden anzeigen",
    "settings.viewApiDocs": "API-Dokumentation anzeigen →",
    "settings.connectedSystems": "Verbundene Systeme",
    "settings.systemName": "Systemname",
    "settings.lastSync": "Letzte Synchronisation",
    "settings.noSystemsConnected": "Noch keine externen Systeme verbunden",
    "settings.riskAssessmentIntervals": "Risikobewertungsintervalle",
    "settings.riskAssessmentIntervalsDesc":
      "Wiederkehrende Risikobewertungspläne einrichten",
    "settings.riskIntervalConfig":
      "Risikobewertungs-Intervallkonfiguration kommt bald...",
    "settings.auditCategories": "Audit-Kategorien",
    "settings.auditIntervals": "Audit-Intervalle",
    "settings.auditIntervalsDesc":
      "Audit-Planung und -Häufigkeit konfigurieren",
    "settings.auditIntervalConfig":
      "Audit-Intervallkonfiguration kommt bald...",
    "settings.notificationLogic": "Benachrichtigungslogik",
    "settings.notificationLogicDesc":
      "Automatisierte Benachrichtigungen und Erinnerungen einrichten",
    "settings.notificationConfig":
      "Benachrichtigungslogik-Konfiguration kommt bald...",

    // G-Investigations (Medical Care)
    "gcode.title": "G-Untersuchungsliste",
    "gcode.description":
      "Wähle hier die für dein Unternehmen relevanten G-Untersuchungen aus.",
    "gcode.saveButton": "Ausgewählte G-Codes speichern",
    "gcode.selectAll": "Alle auswählen",
    "gcode.deselectAll": "Alle abwählen",
    "gcode.selectedCount": "ausgewählt",
    "gcode.of": "von",
    "gcode.G1.1": "Silikogener Staub",
    "gcode.G1.2": "Asbestfaserhaltiger Staub",
    "gcode.G1.3": "künstliche mineralischer Staub der Kat 1 oder 2",
    "gcode.G1.4": "allgemeiner Staub",
    "gcode.G2": "Blei oder seine verbindungen",
    "gcode.G3": "Bleialkyle",
    "gcode.G4":
      "Gefahrstoffe, die Hautkrebs oder zur Krebsbildung neigende Hautveränderungen hervorrufen",
    "gcode.G5": "Glykoldinitrat oder Glycerintrinitrat",
    "gcode.G6": "Schwefelkohlenstoff",
    "gcode.G7": "Kohlenmonoxid",
    "gcode.G8": "Benzol",
    "gcode.G9": "Quecksilber oder seine verbindungen",
    "gcode.G10": "Methanol",
    "gcode.G11": "Schwefelwasserstoff",
    "gcode.G12": "Phosphor (weiß)",
    "gcode.G13": "Tetrachlormethan (Tetrachlorkohlenstoff)",
    "gcode.G14": "Trichlorethen (Trichlorethylen)",
    "gcode.G15": "Chrom-VI-Verbindungen",
    "gcode.G16": "Arsen oder seine Verbindungen",
    "gcode.G17": "Tetrachlorethen",
    "gcode.G18": "1,1,2,2-Tetrachlorethan oder Perchlorthan",
    "gcode.G19": "Dimethylformamid",
    "gcode.G20": "Lärm",
    "gcode.G21": "Kälte",
    "gcode.G22": "Säureschäden der Zähne",
    "gcode.G23": "obstruktive Atemwegserkrankungen",
    "gcode.G24": "Hauterkrankungen (mit Ausnahme von Hautkrebs)",
    "gcode.G25": "Fahr-, Steuer- und Überwachungstätigkeiten",
    "gcode.G26": "Atemschutzgeräte",
    "gcode.G27": "Isocyanate",
    "gcode.G28": "Monochlormethan (Chlormethan, Methylchlorid)",
    "gcode.G29": "Xylol / Toluol",
    "gcode.G30": "Hitze",
    "gcode.G31": "Überdruck",
    "gcode.G32": "Cadmium und seine Verbindungen",
    "gcode.G33": "aromatische Nitro- und Aminoverbindungen",
    "gcode.G34": "Fluor und seine anorganische Verbindungen",
    "gcode.G35":
      "Arbeitsaufenthalt im Ausland unter besonderen klimatischen und gesundheitlichen Belastungen",
    "gcode.G36": "Vinylchlorid",
    "gcode.G37": "Bildschirmarbeit",
    "gcode.G38": "Nickelstäube",
    "gcode.G39": "Schweißrauche",
    "gcode.G40": "Krebs erzeugende und Erbgut verändernde Gefahrstoffe",
    "gcode.G41": "Absturzgefahren",
    "gcode.G42": "Infektionsgefahren",
    "gcode.G43": "Biotechnologie",
    "gcode.G44": "Hartholzstäube",
    "gcode.G45": "Styrol",
    "gcode.G46":
      "Belastungen des Muskel- und Skelettapparates einschl. Vibrationen",
  },
  en: {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome":
      "Welcome back! Here's your safety management overview.",
    "dashboard.setupCompany": "Set Up Company",
    "dashboard.totalEmployees": "Total Employees",
    "dashboard.overdueObligations": "Overdue HSE Obligations",
    "dashboard.last7Days": "Last 7 Days",
    "dashboard.incidents": "Incident Reports",
    "dashboard.hazards": "Hazard Reports",
    "dashboard.needsAttention": "⚠️ Needs attention",
    "dashboard.newReports": "📊 New reports",
    "dashboard.thisMonth": "+5 this month",
    "dashboard.healthCheckups": "Health Check-ups",
    "dashboard.healthCheckupsDesc": "Status of employee health assessments",
    "dashboard.taskOverview": "Task Overview",
    "dashboard.upcomingTasks": "Upcoming tasks",
    "dashboard.completedTasks": "Completed tasks",
    "dashboard.showUpcoming": "Show Upcoming",
    "dashboard.showCompleted": "Show Completed",
    "dashboard.noTasks": "No tasks",
    "dashboard.assignedTo": "Assigned to:",
    "dashboard.unassigned": "Unassigned",
    "dashboard.due": "Due:",
    "dashboard.notSet": "Not set",
    "dashboard.planned": "Planned",
    "dashboard.dueStatus": "Due",
    "dashboard.completed": "Completed",
    "dashboard.cancelled": "Cancelled",
    "dashboard.assigned": "Assigned",
    "dashboard.in progress": "In Progress",
    "dashboard.expired": "Expired",
    "dashboard.high": "High",
    "dashboard.medium": "Medium",
    "dashboard.low": "Low",
    "dashboard.urgent": "Urgent",
    "dashboard.normal": "Normal",

    // Profile
    "dashboard.investigationsByStatus": "Investigations by Status",
    "dashboard.investigationStatusOverview": "Overview of all investigation status",
    "dashboard.upcoming": "Upcoming",
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your account information",
    "profile.saveChanges": "Save Changes",
    "profile.general": "General",
    "profile.security": "Security",
    "profile.preferences": "Preferences",
    "profile.picture": "Profile Picture",
    "profile.pictureDesc": "Update your profile picture",
    "profile.changePicture": "Change Picture",
    "profile.pictureFormat": "JPG, PNG or GIF. Max size 2MB",
    "profile.personalInfo": "Personal Information",
    "profile.personalInfoDesc": "Update your personal details",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.emailNote": "Email cannot be changed",
    "profile.role": "Role:",
    "profile.companyId": "Company ID:",
    "profile.editProfile": "Edit Profile",
    "profile.changePassword": "Change Password",
    "profile.changePasswordDesc":
      "Update your password to keep your account secure",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm New Password",
    "profile.updatePassword": "Update Password",
    "profile.twoFactor": "Two-Factor Authentication",
    "profile.twoFactorDesc": "Add an extra layer of security to your account",
    "profile.enable2FA": "Enable 2FA",
    "profile.notifications": "Notifications",
    "profile.notificationsDesc": "Manage how you receive notifications",
    "profile.emailNotifications": "Email Notifications",
    "profile.emailNotificationsDesc":
      "Receive email updates about your activity",
    "profile.smsNotifications": "SMS Notifications",
    "profile.smsNotificationsDesc": "Receive SMS alerts for urgent matters",
    "profile.languageSettings": "Language Settings",
    "profile.languageSettingsDesc": "Choose your preferred language",
    "profile.language": "Language",
    "profile.german": "German",
    "profile.english": "English",
    "profile.updated": "Profile Updated",
    "profile.updatedDesc":
      "Your profile information has been saved successfully.",

    // Common
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.pickDate": "Pick a date",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading...",
    "common.note": "Note",

    // Employees
    "employees.title": "Employees",
    "employees.description": "Manage your company's employee records",
    "employees.addEmployee": "Add Employee",
    "employees.addNew": "Add New Employee",
    "employees.enterDetails": "Enter employee details below",
    "employees.employeeNumber": "Employee Number",
    "employees.firstName": "First Name",
    "employees.lastName": "Last Name",
    "employees.email": "Email",
    "employees.emailOptional": "Email (Optional)",
    "employees.jobRole": "Job Role",
    "employees.jobRolePlaceholder": "Enter or select job role",
    "employees.department": "Department",
    "employees.departmentPlaceholder": "Enter or select department",
    "employees.hireDate": "Hire Date",
    "employees.status": "Status",
    "employees.active": "Active",
    "employees.inactive": "Inactive",
    "employees.search": "Search employees...",
    "employees.noEmployees": "No employees found",
    "employees.adding": "Adding...",
    "employees.addSuccess": "Employee added successfully",
    "employees.addError": "Failed to add employee",
    "employees.loadError": "Failed to load employees",
    "employees.noDeletePermission": "You do not have permission to delete employees",
    "employees.noCreatePermission": "You do not have permission to create employees",
    "employees.noEditPermission": "You do not have permission to edit employees",
    "employees.name": "Name",
    "employees.filterStatus": "Status Filter",
    "employees.filterDepartment": "Department Filter",
    "employees.allEmployees": "All Employees",
    "employees.activeOnly": "Active Only",
    "employees.inactiveOnly": "Inactive Only",
    "employees.allDepartments": "All Departments",
    "employees.selectDepartment": "Select department",
    "employees.details": "Employee Details & Records",
    "employees.info": "Info",
    "employees.riskProfile": "Risk Profile",
    "employees.training": "Training",
    "employees.tasks": "Tasks",
    "employees.exposureGroup": "Exposure Group",
    "employees.riskAssignments":
      "Risk assessments assigned to this employee will appear here.",
    "employees.trainingRecords":
      "Training records for this employee will appear here.",
    "employees.assignedTasks":
      "Tasks assigned to this employee will appear here.",
    "employees.required": "Required",
    "employees.optional": "Optional",
    "employees.enterJobRole": "Enter job role (e.g., Safety Officer)",
    "employees.noCompanyId":
      "No company ID found. You need to be assigned to a company first.",
    "employees.import": "Import",
    "employees.export": "Export",
    "employees.importEmployees": "Import Employees",
    "employees.exportAs": "Export as",
    "employees.selectFile": "Select file (.xlsx, .xls, .csv)",
    "employees.importSuccess": "Employees imported successfully",
    "employees.importError": "Error importing employees",
    "employees.exportSuccess": "Employees exported successfully",
    "employees.exportError": "Error exporting employees",
    "employees.importing": "Importing...",
    "employees.exporting": "Exporting...",
    "employees.invalidFile": "Invalid file. Please use .xlsx, .xls or .csv",
    "employees.noValidData": "No valid data found in file",

    // Navigation / Layout
    "nav.dashboard": "Dashboard",
    "nav.employees": "Employees",
    "nav.messages": "Messages",
    "nav.investigations": "Investigations",
    "nav.riskAssessments": "Risk Assessments",
    "nav.measures": "Measures",
    "nav.training": "Training",
    "nav.trainings": "Trainings",
    "nav.incidents": "Incidents",
    "nav.audits": "Audits",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.hseHub": "HSE Hub",
    "nav.welcomeToHseHub": "Welcome to HSE Hub",
    "nav.profile": "Profile",
    "nav.invoices": "Invoices",
    "nav.darkMode": "Dark mode",
    "nav.language": "Language",
    "nav.signOut": "Sign out",
    "nav.company": "Company",
    "nav.user": "User",

    // Investigations
    "investigations.title": "Investigations",
    "investigations.manage": "Manage Incident Investigations",
    "investigations.new": "New Investigation",
    "investigations.edit": "Edit",
    "investigations.id": "Investigation ID",
    "investigations.relatedIncident": "Related Incident",
    "investigations.startDate": "Start Date",
    "investigations.assignedTo": "Assigned To",
    "investigations.status": "Status",
    "investigations.priority": "Priority",
    "investigations.description": "Description",
    "investigations.findings": "Findings",
    "investigations.recommendations": "Recommendations",
    "investigations.search": "Search investigations...",
    "investigations.exportPDF": "Export as PDF",
    "investigations.filterStatus": "Filter Status",
    "investigations.filterPriority": "Filter Priority",
    "investigations.open": "Open",
    "investigations.inProgress": "In Progress",
    "investigations.completed": "Completed",
    "investigations.planned": "Planned",
    "investigations.closed": "Closed",
    "investigations.low": "Low",
    "investigations.medium": "Medium",
    "investigations.high": "High",
    "investigations.critical": "Critical",
    "investigations.unassigned": "Unassigned",
    "investigations.actions": "Actions",
    "investigations.allInvestigations": "All Investigations",
    "investigations.employeesWithInvestigations":
      "Employees with G-Investigations (planned/due by filter)",
    "investigations.termsDueDates": "Terms and Due Dates (per investigation)",
    "investigations.overview": "Health Examinations Overview",
    "investigations.employeeView": "Employee View",
    "investigations.dateView": "Date View",
    "investigations.checkupView": "Checkup View",
    "investigations.newInvestigation": "New Investigation",
    "investigations.editInvestigation": "Edit Investigation",
    "investigations.investigationDetails": "Enter G-Investigation details",
    "investigations.gCode": "G-Code",
    "investigations.employee": "Employee",
    "investigations.selectEmployee": "Select employee",
    "investigations.none": "None",
    "investigations.dueDate": "Due Date",
    "investigations.appointmentDate": "Appointment",
    "investigations.doctor": "Doctor",
    "investigations.doctorName": "Doctor's name",
    "investigations.investigationDescription": "Investigation description",
    "investigations.cancel": "Cancel",
    "investigations.update": "Update",
    "investigations.create": "Create",
    "investigations.employees": "Employees",
    "investigations.appointments": "Appointments",
    "investigations.searchPlaceholder": "Search (Name, Department)",
    "investigations.plannedOrDue": "Planned or Due",
    "investigations.allTypes": "All Types",
    "investigations.allDepartments": "All Departments",
    "investigations.allGroups": "All Groups",
    "investigations.fromDate": "From Date",
    "investigations.toDate": "To Date",
    "investigations.name": "Name",
    "investigations.firstName": "First Name",
    "investigations.department": "Department",
    "investigations.location": "Location",
    "investigations.group": "Group",
    "investigations.gInvestigations": "G-Investigations",
    "investigations.noInvestigations":
      "No investigations found. Create a new one.",
    "investigations.investigation": "Investigation",
    "investigations.success": "Success",
    "investigations.investigationUpdated": "Investigation updated successfully",
    "investigations.updated": "Investigation updated successfully",
    "investigations.created": "Investigation created successfully",
    "investigations.noResults": "No investigations found",

    // Health Check-Ups  
    "checkups.title": "Health Check-Ups (G-Investigations)",
    "checkups.description": "Manage employee health check-ups and medical examinations",
    "checkups.addCheckup": "Add Check-Up",
    "checkups.noCheckups": "No check-ups scheduled",
    "checkups.done": "Done",
    "checkups.due": "Due",
    "checkups.planned": "Planned",
    "checkups.open": "Open",
    "checkups.investigation": "Investigation",
    "checkups.dueDate": "Due",
    "checkups.completed": "Completed",
    "checkups.appointment": "Appointment",
    "checkups.complete": "Complete",
    "checkups.uploadCertificate": "Upload Certificate",

    "measures.edit": "Edit Measure",
    "measures.measureTitle": "Measure Title",
    "measures.description": "Description",
    "measures.type": "Measure Type",
    "measures.status": "Status",
    "measures.responsiblePerson": "Responsible Person",
    "measures.dueDate": "Due Date",
    "measures.completionDate": "Completion Date",
    "measures.verificationMethod": "Verification Method",
    "measures.search": "Search measures...",
    "measures.exportPDF": "Export PDF",
    "measures.filterStatus": "Filter Status",
    "measures.filterType": "Filter Type",
    "measures.preventive": "Preventive",
    "measures.corrective": "Corrective",
    "measures.improvement": "Improvement",
    "measures.planned": "Planned",
    "measures.inProgress": "In Progress",
    "measures.completed": "Completed",
    "measures.cancelled": "Cancelled",
    "measures.actions": "Actions",
    "measures.noDeadline": "No deadline",

    // Training
    "training.title": "Training",
    "training.subtitle": "Training & Qualification Management",
    "training.records": "Training Records",
    "training.assign": "Assign Training",
    "training.employee": "Employee",
    "training.trainingType": "Training Type",
    "training.assignedDate": "Assigned Date",
    "training.expiryDate": "Expiry Date",
    "training.status": "Status",
    "training.search": "Search trainings...",
    "training.selectEmployee": "Select employee",
    "training.selectType": "Select training type",
    "training.assigned": "Assigned",
    "training.inProgress": "In Progress",
    "training.completed": "Completed",
    "training.expired": "Expired",
    "training.actions": "Actions",
    "training.createCourse": "Create Course",
    "training.courseName": "Course Name",
    "training.courseDescription": "Course Description",
    "training.courseContent": "Course Content",
    "training.manageLessons": "Manage lessons and content for this course",
    "training.addLesson": "Add Lesson",
    "training.uploadLessons": "Upload Lessons",
    "training.newLesson": "New Lesson",
    "training.lessonName": "Lesson Name",
    "training.lessonType": "Type",
    "training.noCourses": "No training records found",
    "training.noCoursesDesc": "Assign training to employees to get started",
    "training.noLessons": "No lessons yet",
    "training.noLessonsDesc": 'Click "Add Lesson" to add content',
    "training.draft": "Draft",
    "training.published": "Published",
    "training.unterkapitel": "Subchapter",
    "training.videoAudio": "Video/Audio",
    "training.pdf": "PDF",
    "training.text": "Text",
    "training.websiteLink": "Website Link",
    "training.zipFile": "ZIP File",
    "training.videoLink": "Video Link",
    "training.pdfLink": "PDF Link",
    "training.websiteLinkUrl": "Website URL",
    "training.zipFileLink": "ZIP File Link",
    "training.textContent": "Text Content",
    "training.enterTextContent": "Enter text content...",
    "training.lessonDetails": "Lesson Details",
    "training.openLink": "Open Link",
    "training.cancel": "Cancel",
    "training.lesson": "Lesson",
    "training.general": "General",
    "training.chapters": "Chapters",
    "training.videoAudioLesson": "Video/Audio Lesson",
    "training.learnMoreEditor": "Learn more about the course editor",
    "training.enterLessonName": "Enter lesson name",
    "training.shortDescription": "Short Description",
    "training.shortDescriptionPlaceholder": "Short description of the lesson...",
    "training.videoAudioNote": "Note on Video and Audio Formats",
    "training.videoAudioFormats": "Video & Audio formats up to 25GB",
    "training.recordVideo": "Record Video",
    "training.importVideo": "Import Video",
    "training.manageChapters": "Manage Chapters",
    "training.addLessonsToSubchapter": "Add lessons to this subchapter",
    "training.chapterManagementComingSoon": "Chapter management coming soon",
    "common.saving": "Saving...",

    // Incidents
    "incidents.title": "Incidents & Investigations",
    "incidents.description":
      "Track workplace incidents, near misses, and injuries with root cause analysis",
    "incidents.subtitle": "Incidents & Near Misses",
    "incidents.new": "New Incident",
    "incidents.edit": "Edit Incident",
    "incidents.incidentNumber": "Incident #",
    "incidents.incidentTitle": "Incident Title",
    "incidents.type": "Type",
    "incidents.severity": "Severity",
    "incidents.date": "Date",
    "incidents.location": "Location",
    "incidents.department": "Department",
    "incidents.affectedEmployee": "Affected Employee",
    "incidents.reportedBy": "Reported By",
    "incidents.rootCause": "Root Cause Analysis",
    "incidents.immediateActions": "Immediate Actions Taken",
    "incidents.investigationStatus": "Investigation Status",
    "incidents.search": "Search incidents...",
    "incidents.searchPlaceholder": "Search incidents...",
    "incidents.filterType": "Filter by type",
    "incidents.filterByType": "Filter by type",
    "incidents.filterSeverity": "Filter by severity",
    "incidents.filterBySeverity": "Filter by severity",
    "incidents.injury": "Injury",
    "incidents.nearMiss": "Near Miss",
    "incidents.propertyDamage": "Property Damage",
    "incidents.environmental": "Environmental",
    "incidents.other": "Other",
    "incidents.minor": "Minor",
    "incidents.moderate": "Moderate",
    "incidents.serious": "Serious",
    "incidents.critical": "Critical",
    "incidents.fatal": "Fatal",
    "incidents.actions": "Actions",
    "incidents.total": "Total Incidents",
    "incidents.injuries": "Injuries",
    "incidents.nearMisses": "Near Misses",
    "incidents.underInvestigation": "Under Investigation",
    "incidents.reports": "Incident Reports",
    "incidents.reportsDesc":
      "Complete list of all workplace incidents and near misses",
    "incidents.reportIncident": "Report Incident",
    "incidents.editIncident": "Edit Incident",
    "incidents.reportNew": "Report New Incident",
    "incidents.documentDesc":
      "Document a workplace incident or near miss for investigation",
    "incidents.titlePlaceholder": "Brief description of the incident",
    "incidents.descriptionPlaceholder": "Detailed description of what happened",
    "incidents.locationPlaceholder": "Where did it occur?",
    "incidents.selectDepartment": "Select department",
    "incidents.selectEmployee": "Select employee",
    "incidents.immediateActionsPlaceholder":
      "What was done immediately after the incident?",
    "incidents.rootCausePlaceholder": "What caused this incident?",
    "incidents.open": "Open",
    "incidents.inProgress": "In Progress",
    "incidents.closed": "Closed",
    "incidents.report": "Report",
    "incidents.incident": "Incident",
    "incidents.allTypes": "All Types",
    "incidents.allSeverities": "All Severities",
    "incidents.noIncidents": "No incidents found. Report one to get started.",
    "incidents.status": "Status",
    "incidents.affected": "Affected",

    // Risk Assessments
    "risks.title": "Risk Assessments",
    "risks.subtitle": "Manage hazard assessments",
    "risks.new": "New Risk Assessment",
    "risks.riskTitle": "Risk Title",
    "risks.description": "Description",
    "risks.category": "Risk Category",
    "risks.department": "Department",
    "risks.likelihood": "Likelihood",
    "risks.severity": "Severity",
    "risks.riskScore": "Risk Score",
    "risks.riskLevel": "Risk Level",
    "risks.mitigation": "Mitigation Measures",
    "risks.assessmentDate": "Assessment Date",
    "risks.search": "Search risks...",
    "risks.selectCategory": "Select category",
    "risks.selectDepartment": "Select department",
    "risks.critical": "Critical",
    "risks.high": "High",
    "risks.medium": "Medium",
    "risks.low": "Low",
    "risks.basicInformation": "Basic Information",
    "risks.hazardAssessment": "Hazard Assessment & Measures",
    "risks.measures": "Measures",
    "risks.hazardCategory": "Hazard Category",
    "risks.selectHazardCategory": "Select...",
    "risks.shortDescription": "Description",
    "risks.shortDescriptionPlaceholder": "Short description",
    "risks.primaBefore": "PRIMA (before)",
    "risks.postAfter": "POST (after)",
    "risks.probabilityBefore": "Probability of occurrence (before)",
    "risks.probabilityAfter": "Probability of occurrence (after)",
    "risks.damageExtentBefore": "Extent of damage (before)",
    "risks.damageExtentAfter": "Extent of damage (after)",
    "risks.riskScoreCalculated": "Risk Score (calculated)",
    "risks.location": "Location",
    "risks.selectLocation": "Select location",
    "risks.exposureGroup": "Exposure Group",
    "risks.selectExposureGroup": "Select exposure group",
    "risks.lineManager": "User",
    "risks.selectLineManager": "Select user",
    "risks.responsiblePerson": "Responsible Person",
    "risks.selectManager": "Select manager",
    "risks.dueDate": "Due Date",
    "risks.uploadDocuments": "Upload Documents",
    "risks.chooseFile": "Choose file | None selected",
    "risks.addMeasure": "+ Add Measure",
    "risks.addMeasureButton": "Add Measure",
    "risks.buildingBlock": "Building Block",
    "risks.selectBuildingBlock": "Select building block",
    "risks.progressStatus": "Progress Status",
    "risks.notStarted": "Not Started",
    "risks.notes": "Notes",
    "risks.back": "← Back",
    "risks.nextSlide": "Next Slide →",
    "risks.step1": "Step 1",
    "risks.step2": "Step 2",
    "risks.step3": "Step 3",

    // Audits
    "audits.title": "Audits",
    "audits.subtitle": "Safety Audits",
    "audits.new": "New Audit",
    "audits.auditTitle": "Audit Title",
    "audits.category": "Audit Category",
    "audits.department": "Department",
    "audits.scheduledDate": "Scheduled Date",
    "audits.status": "Status",
    "audits.findings": "Findings",
    "audits.deficiencies": "Deficiencies Found",
    "audits.search": "Search audits...",
    "audits.selectCategory": "Select category",
    "audits.selectDepartment": "Select department",
    "audits.planned": "Planned",
    "audits.inProgress": "In Progress",
    "audits.completed": "Completed",
    "audits.actions": "Actions",
    "audits.isoStandard": "ISO Standard",
    "audits.selectISOStandard": "Select ISO Standard",
    "audits.responsiblePerson": "Responsible Person",
    "audits.selectPerson": "Select person",
    "audits.scope": "Scope",
    "audits.scopePlaceholder": "e.g. No scope defined",
    "audits.allStatus": "All Status",
    "audits.allTemplates": "All Templates",
    "audits.template": "Template",
    "audits.progress": "Progress",
    "audits.details": "Details",
    "audits.pdf": "PDF",
    "audits.delete": "Delete",
    "audits.deleteConfirm": "Delete Audit?",
    "audits.deleteMessage": "Are you sure you want to delete this audit? This action cannot be undone.",
    "audits.createAudit": "Create Audit",
    "audits.notAssigned": "Not assigned",
    "audits.noAudits": "No audits found",
    "audits.createFirst": "Create your first audit",
    "audits.auditCenter": "Audit and Compliance Center",
    "audits.standardizedAudits": "Standardized Audits, Reports and Evidence",
    "audits.checklist": "Checklist",
    "audits.checklistItems": "Checklist Items",
    "audits.status.pending": "Pending",
    "audits.status.completed": "Completed",
    "audits.status.failed": "Failed",
    "audits.status.notApplicable": "Not Applicable",
    "audits.notes": "Notes",
    "audits.notesPlaceholder": "Notes for this checkpoint...",
    "audits.pdfExport": "PDF Export",
    "audits.descriptionPlaceholder": "Audit description...",

    // Common Actions
    "common.create": "Create",
    "common.update": "Update",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.all": "All",
    "common.none": "None",
    "common.select": "Select",
    "common.optional": "Optional",
    "common.required": "Required",
    "common.actions": "Actions",
    "common.by": "By",
    "common.status": "Status",
    "common.close": "Close",
    "common.success": "Success",
    "common.error": "Error",
    "common.savingError": "Error saving",
    "common.createdOn": "Created on",
    "common.pdfExported": "PDF exported successfully",
    "common.lastName": "Last Name",
    "common.firstName": "First Name",
    "common.department": "Department",
    "common.location": "Location",
    "common.group": "Group",
    "common.employee": "Employee",
    "common.allDepartments": "All Departments",
    "common.allGroups": "All Groups",
    "common.fromDate": "From Date",
    "common.toDate": "To Date",
    "common.yes": "Yes",
    "common.no": "No",

    // Reports
    "reports.title": "HSE Reports & Analytics",
    "reports.subtitle": "Comprehensive compliance and performance dashboards",
    "reports.exportPDF": "Export PDF",
    "reports.totalEmployees": "Total Employees",
    "reports.activeWorkforce": "Active workforce",
    "reports.riskAssessments": "Risk Assessments",
    "reports.totalGBU": "Total GBU assessments",
    "reports.safetyAudits": "Safety Audits",
    "reports.completed": "completed",
    "reports.trainingCompliance": "Training Compliance",
    "reports.overview": "Overview",
    "reports.trainingMatrix": "Training Matrix",
    "reports.incidents": "Incidents",
    "reports.measures": "Measures",
    "reports.auditCompletion": "Audit Completion Status",
    "reports.auditMetrics": "Safety audit performance metrics",
    "reports.totalAudits": "Total Audits",
    "reports.taskCompletion": "Task Completion Status",
    "reports.taskTracking": "Corrective action tracking",
    "reports.totalTasks": "Total Tasks",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "System Configuration",
    "settings.team": "Team",
    "settings.teamDesc": "Invite and manage team members",
    "settings.userRoles": "User Roles & Permissions (RBAC)",
    "settings.rolesDesc":
      "Define roles and their access permissions across the system",
    "settings.permissionUpdated": "Permission updated successfully",
    "settings.configuration": "Configuration",
    "settings.configDesc": "Locations, departments, approvals",
    "settings.catalogs": "Catalogs & Content",
    "settings.catalogsDesc": "Hazards, measures, risk matrix",
    "settings.intervals": "Intervals and Deadlines",
    "settings.intervalsDesc": "Risk assessments, audits, notifications",
    "settings.medicalCare": "Occupational Medical Care",
    "settings.medicalDesc": "G-Investigations list",
    "settings.profileFields": "Profile Fields",
    "settings.profileFieldsDesc": "Define custom fields",
    "settings.profileFieldsTitle": "Profile Fields",
    "settings.profileFieldsSubtitle": "Create templates with fields for candidate profiles. Templates can be assigned as jobs in the editor",
    "settings.addProfileField": "Add Field",
    "settings.fieldName": "Field Name",
    "settings.fieldLabel": "Field Label",
    "settings.fieldType": "Field Type",
    "settings.extractedFromResume": "Extracted from Resume",
    "settings.fieldRequired": "Required Field",
    "settings.fieldTypeText": "Text",
    "settings.fieldTypeNumber": "Number",
    "settings.fieldTypeDate": "Date",
    "settings.fieldTypeBoolean": "Yes/No",
    "settings.noProfileFields": "No fields found. Create your first field.",
    "settings.addRole": "Add Custom Role",
    "settings.createRole": "Create Custom Role",
    "settings.roleDesc":
      "Enter a name for the new role. You can configure permissions after creation.",
    "settings.rolePlaceholder": "Role name (e.g., Project Manager)",
    "settings.role": "Role",
    "settings.dashboard": "Dashboard",
    "settings.employees": "Employees",
    "settings.healthCheckups": "Health Check-Ups",
    "settings.documents": "Documents",
    "settings.reports": "Reports",
    "settings.audits": "Audits",
    "settings.settings": "Settings",
    "settings.teamManagement": "Team Management",
    "settings.teamManagementDesc":
      "Manage team members, their access, and user roles",
    "settings.addTeamMember": "Add Team Member",
    "settings.firstName": "First Name",
    "settings.lastName": "Last Name",
    "settings.enterFirstName": "Enter first name",
    "settings.enterLastName": "Enter last name",
    "settings.enterEmail": "Enter email",
    "settings.userRole": "User Role",
    "settings.selectRole": "Select role",
    "settings.name": "Name",
    "settings.email": "Email",
    "settings.status": "Status",
    "settings.noTeamMembers":
      "No team members found. Add team members to invite them to the platform.",
    "settings.locations": "Locations",
    "settings.locationsDesc": "Manage company locations and sites",
    "settings.locationManagement": "Location management coming soon...",
    "settings.departments": "Departments",
    "settings.approvalProcess": "Approval Process",
    "settings.approvalProcessDesc":
      "Configure approval workflows (Department → Approver)",
    "settings.addApprovalWorkflow": "Add Approval Workflow",
    "settings.selectDepartment": "Select department",
    "settings.department": "Department",
    "settings.approver": "Approver",
    "settings.selectApprover": "Select approver",
    "settings.noApprovalWorkflows":
      "No approval workflows configured. Add departments above to get started.",
    "settings.exposureGroups": "Exposure Groups",
    "settings.hazardCategories": "Hazard Categories",
    "settings.hazardCategoriesDesc":
      "Manage hazard severity levels - Predefined values cannot be deleted",
    "settings.addCustomCategory": "Add Custom Category",
    "settings.addCustomHazardCategory": "Add Custom Hazard Category",
    "settings.createCustomHazardCategory":
      "Create a custom hazard category for your organization",
    "settings.categoryName": "Category Name",
    "settings.predefined": "Predefined",
    "settings.custom": "Custom",
    "settings.measureBuildingBlocks": "Measure Building Blocks",
    "settings.measureBuildingBlocksDesc": "Define reusable measure templates",
    "settings.measureManagement": "Measure building blocks coming soon...",
    "settings.isoSelection": "ISO Selection & Criteria",
    "settings.isoSelectionDesc":
      "Select applicable ISO standards and configure criteria",
    "settings.selectISOStandards": "Select ISO Standards",
    "settings.customISOStandards": "Custom ISO Standards",
    "settings.enterISOName": "Enter ISO name (e.g., ISO 27001)",
    "settings.add": "Add",
    "settings.criteriaForISOs": "Criteria for Selected ISOs",
    "settings.compact": "Compact",
    "settings.complete": "Complete",
    "settings.criteria": "Criteria",
    "settings.criteriaNote":
      "Criteria must be adjusted at the top; depending on what has been selected, they will appear or not.",
    "settings.enterNewCriterion": "Enter new criterion...",
    "settings.criteriaInfoNote":
      "The selected criteria will be used when creating audits and checklists. You can add or remove custom criteria at any time.",
    "settings.isoCriteriaManagement": "ISO Criteria Management",
    "settings.isoCriteriaManagementDesc": "View and manage criteria for selected ISO standards",
    "settings.noISOSelected": "No ISO standards selected",
    "settings.selectISOAbove": "Select an ISO standard above to view its criteria",
    "settings.sections": "sections",
    "settings.subsections": "subsections",
    "settings.implemented": "Implemented",
    "settings.satisfied": "Satisfied",
    "settings.addItem": "Add",
    "settings.editItem": "Edit",
    "settings.addDetails": "Add additional details or notes...",
    "settings.noItems": "No items found. Click",
    "settings.toCreate": "to create",
    "settings.adding": "Adding...",
    "settings.success": "Success",
    "settings.categoryCreated": "Category created successfully",
    "settings.error": "Error",
    "settings.apiIntegration": "API Integration",
    "settings.apiIntegrationDesc":
      "Connect external systems and manage API access",
    "settings.apiIntegrationNav": "External system connections",
    "settings.apiToken": "API Token",
    "settings.generateNewToken": "Generate New Token",
    "settings.apiTokenDesc":
      "Use this token to authenticate API requests from external systems",
    "settings.apiDocumentation": "API Documentation",
    "settings.baseUrl": "Base URL:",
    "settings.apiDocsDesc":
      "View full API documentation and integration guides",
    "settings.viewApiDocs": "View API Docs →",
    "settings.connectedSystems": "Connected Systems",
    "settings.systemName": "System Name",
    "settings.lastSync": "Last Sync",
    "settings.noSystemsConnected": "No external systems connected yet",
    "settings.riskAssessmentIntervals": "Risk Assessment Intervals",
    "settings.riskAssessmentIntervalsDesc":
      "Set up recurring risk assessment schedules",
    "settings.riskIntervalConfig":
      "Risk assessment interval configuration coming soon...",
    "settings.auditCategories": "Audit Categories",
    "settings.auditIntervals": "Audit Intervals",
    "settings.auditIntervalsDesc": "Configure audit scheduling and frequency",
    "settings.auditIntervalConfig":
      "Audit interval configuration coming soon...",
    "settings.notificationLogic": "Notification Logic",
    "settings.notificationLogicDesc":
      "Set up automated notifications and reminders",
    "settings.notificationConfig":
      "Notification logic configuration coming soon...",

    // G-Investigations (Medical Care)
    "gcode.title": "G-Investigations List",
    "gcode.description":
      "Select relevant German G-codes for occupational medical examinations",
    "gcode.saveButton": "Save Selected G-Codes",
    "gcode.selectAll": "Select All",
    "gcode.deselectAll": "Deselect All",
    "gcode.selectedCount": "selected",
    "gcode.of": "of",
    "gcode.G1.1": "Silicogenic dust",
    "gcode.G1.2": "Asbestos-containing dust",
    "gcode.G1.3": "Artificial mineral dust of category 1 or 2",
    "gcode.G1.4": "General dust",
    "gcode.G2": "Lead or its compounds",
    "gcode.G3": "Tetraethyl lead",
    "gcode.G4":
      "Hazardous substances that cause skin cancer or skin changes prone to cancer formation",
    "gcode.G5": "Glycol dinitrate or glycerol trinitrate",
    "gcode.G6": "Carbon disulfide",
    "gcode.G7": "Carbon monoxide",
    "gcode.G8": "Benzene",
    "gcode.G9": "Mercury or its compounds",
    "gcode.G10": "Methanol",
    "gcode.G11": "Hydrogen sulfide",
    "gcode.G12": "Phosphorus (white)",
    "gcode.G13": "Carbon tetrachloride",
    "gcode.G14": "Trichloroethylene",
    "gcode.G15": "Chromium VI compounds",
    "gcode.G16": "Arsenic or its compounds",
    "gcode.G17": "Tetrachloroethylene",
    "gcode.G18": "1,1,2,2-Tetrachloroethane or perchloroethane",
    "gcode.G19": "Dimethylformamide",
    "gcode.G20": "Noise",
    "gcode.G21": "Cold",
    "gcode.G22": "Acid damage to teeth",
    "gcode.G23": "Obstructive respiratory diseases",
    "gcode.G24": "Skin diseases (excluding skin cancer)",
    "gcode.G25": "Driving, steering and monitoring activities",
    "gcode.G26": "Respiratory protective equipment",
    "gcode.G27": "Isocyanates",
    "gcode.G28": "Monochloromethane (chloromethane, methyl chloride)",
    "gcode.G29": "Xylene / Toluene",
    "gcode.G30": "Heat",
    "gcode.G31": "Overpressure",
    "gcode.G32": "Cadmium and its compounds",
    "gcode.G33": "Aromatic nitro and amino compounds",
    "gcode.G34": "Fluorine and its inorganic compounds",
    "gcode.G35": "Work abroad under special climatic and health stresses",
    "gcode.G36": "Vinyl chloride",
    "gcode.G37": "Display screen work",
    "gcode.G38": "Nickel dusts",
    "gcode.G39": "Welding fumes",
    "gcode.G40": "Carcinogenic and mutagenic substances",
    "gcode.G41": "Risk of falling",
    "gcode.G42": "Infectious hazards",
    "gcode.G43": "Biotechnology",
    "gcode.G44": "Hardwood dusts",
    "gcode.G45": "Styrene",
    "gcode.G46": "Musculoskeletal stress including vibrations",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  // Default to German (de)
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "de";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
