// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// German-SafeForward — eu-central-1 (Frankfurt) — Produktiv-Projekt
const SUPABASE_URL = "https://mzqypusyxvyuiesuhjcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cXlwdXN5eHZ5dWllc3VoamN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNDQ0MTcsImV4cCI6MjA5NzYyMDQxN30.BLnaiuAJ4pZoEPnAUzKOPXBi6_TGaDKTgc57UO-uWvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});