// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// German-SafeForward — eu-central-1 (Frankfurt) — UAT-Projekt
const SUPABASE_URL = "https://cbjdtpukzvcunpblxlfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiamR0cHVrenZjdW5wYmx4bGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUzMjMwNDYsImV4cCI6MjEwMDg5OTA0Nn0.loV3YSzTa1it16lPOGzvFpSV1ylNoe-HloDQfZDuokk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});